id: A242707A2
title: A Daily 'Hand-Clapping' Practice of Siṃhamukhā
type: translation
source_metadata:
  languages:
  - en
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:49:27.718274
  last_modified_at: 2022-03-01 05:49:27.718281
