id: A242707A2
title: Siṃhamukhā Lineage Prayer
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:49:27.720506
  last_modified_at: 2022-03-01 05:49:27.720509
